import jsPDF from 'jspdf';
import { ACTIVITIES } from './points';

export function generateApprovalPDF(certificate, student, faculty) {
    const doc = new jsPDF();
    const actId = certificate.activityId || certificate.activity_id;
    const activity = certificate.activity_snapshot || certificate.activitySnapshot || ACTIVITIES[actId];

    // Header background
    doc.setFillColor(15, 23, 42); // dark blue
    doc.rect(0, 0, 210, 40, 'F');

    // University name
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.text('APJ Abdul Kalam Technological University', 105, 16, { align: 'center' });

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Activity Points Certificate of Approval — 2024 Scheme', 105, 25, { align: 'center' });

    doc.setFontSize(9);
    doc.text('KTU Activity Point Management System', 105, 33, { align: 'center' });

    // Divider
    doc.setDrawColor(99, 102, 241);
    doc.setLineWidth(1);
    doc.line(14, 44, 196, 44);

    // Student Info Section
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('Student Information', 14, 54);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    const studentInfo = [
        ['Name', student.name || 'Unknown'],
        ['Roll Number', student.rollNo || student.roll_no || 'N/A'],
        ['Department', student.department || 'N/A'],
        ['Student Type', (student.studentType || student.student_type || 'regular').toUpperCase()],
        ['Email', student.email || 'N/A'],
    ];
    let y = 62;
    for (const [label, value] of studentInfo) {
        doc.setFont('helvetica', 'bold');
        doc.text(`${label}:`, 18, y);
        doc.setFont('helvetica', 'normal');
        doc.text(value, 70, y);
        y += 8;
    }

    // Certificate Details Section
    y += 4;
    doc.setFillColor(241, 245, 249);
    doc.roundedRect(14, y - 4, 182, 6 * 8 + 14, 3, 3, 'F');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(15, 23, 42);
    doc.text('Activity Details', 18, y + 4);

    doc.setFontSize(10);
    const details = [
        ['Activity ID', actId || 'N/A'],
        ['Activity Name', activity ? activity.name : (certificate.activityName || 'N/A')],
        ['Group', `Group ${activity ? activity.group : 'N/A'} — ${activity ? activity.category : ''}`],
        ['Level / Type', certificate.selectedLevel || certificate.level_selected || 'N/A'],
        ['Sub-details', certificate.description || 'N/A'],
        ['Date of Activity', certificate.activityDate || (certificate.created_at ? new Date(certificate.created_at).toLocaleDateString('en-IN') : 'N/A')],
    ];
    y += 12;
    for (const [label, value] of details) {
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(100, 116, 139);
        doc.text(`${label}:`, 18, y);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(15, 23, 42);
        const wrapped = doc.splitTextToSize(value, 120);
        doc.text(wrapped, 75, y);
        y += 8;
    }

    // Points Awarded Box
    y += 6;
    doc.setFillColor(99, 102, 241);
    doc.roundedRect(14, y, 182, 20, 3, 3, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Points Awarded:', 22, y + 13);
    doc.setFontSize(20);
    doc.text(`${certificate.pointsAwarded} pts`, 170, y + 13, { align: 'right' });

    // Approval Details
    y += 30;
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('Verification Details', 14, y);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    const approval = [
        ['Approved By', faculty.name || 'System'],
        ['Designation', faculty.designation || 'Faculty'],
        ['Approval Date', certificate.approvedAt || certificate.reviewed_at ? new Date(certificate.approvedAt || certificate.reviewed_at).toLocaleDateString('en-IN') : new Date().toLocaleDateString('en-IN')],
        ['Remarks', certificate.notes || certificate.facultyRemark || 'Approved'],
    ];
    y += 8;
    for (const [label, value] of approval) {
        doc.setFont('helvetica', 'bold');
        doc.text(`${label}:`, 18, y);
        doc.setFont('helvetica', 'normal');
        doc.text(value, 70, y);
        y += 8;
    }

    // Footer
    doc.setFillColor(15, 23, 42);
    doc.rect(0, 280, 210, 17, 'F');
    doc.setTextColor(148, 163, 184);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text('This document is system-generated by the KTU Activity Point Management System.', 105, 288, { align: 'center' });
    doc.text('Verify authenticity with your Student Faculty Advisor.', 105, 294, { align: 'center' });

    // Save
    const sName = student?.name ? student.name.replace(/\s/g, '_') : 'Student';
    const sRoll = student?.rollNo || student?.roll_no || sName;
    const filename = `KTU_ActivityPoints_${sRoll}_${certificate.id}.pdf`;
    doc.save(filename);
    return filename;
}

